  - hosts: localhost
    connection: local
    become: yes

    pre_tasks:
      - name: Update APT Repositories
        apt:
          update_cache: yes
        changed_when: false

    tasks:
      - include: tasks/base-packages.yml
