  - name: ensure required packages are present
    apt:
      name: ['git', 'stow']
      state: present

  - name: checkout dotfiles repository
    git:
      repo: https://github.com/cjrowe/dotfiles.git
      dest: /home/chris/.dotfiles

  - name: "Symlink dotfiles"
    shell: stow -d ~/.dotfiles -t ~/ {{ item }}
    with_items:
      - tmux
      - vim
