  - name: ensure prequisite packages are installed
    apt:
      name: ['libx11-dev', 'libxft-dev', 'libxinerama-dev']
      state: present

  - name: clone dwm
    become_user: chris
    git:
      repo: https://github.com/cjrowe/dwm.git
      version: 6.2
      dest: /home/chris/.suckless/dwm

  - name: clone dmenu
    become_user: chris
    git:
      repo: https://github.com/cjrowe/dmenu.git
      version: 5.0
      dest: /home/chris/.suckless/dmenu

  - name: clone st
    become_user: chris
    git:
      repo: https://github.com/cjrowe/st.git
      version: 0.8.4
      dest: /home/chris/.suckless/st

  - name: clone dwmblocks
    become_user: chris
    git:
      repo: https://github.com/cjrowe/dwmblocks.git
      dest: /home/chris/.suckless/dwmblocks
